import {
  Activity,
  AlertTriangle,
  BarChart3,
  BookOpen,
  Building2,
  Calculator,
  CircleDollarSign,
  ClipboardCheck,
  ClipboardList,
  CreditCard,
  FileImage,
  FileCode2,
  FileText,
  Gauge,
  HelpCircle,
  Landmark,
  Languages,
  Link2,
  Mail,
  MapPinned,
  Megaphone,
  Menu,
  MessageSquare,
  Package,
  PackagePlus,
  Percent,
  ReceiptText,
  Rocket,
  SearchCheck,
  Send,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Smartphone,
  Tags,
  Truck,
  UploadCloud,
  Workflow,
} from 'lucide-react';

export const appNavigationGroups = [
  {
    label: 'Baslangic',
    items: [
      { to: '/', label: 'Baslangic', icon: Gauge, end: true },
    ],
  },
  {
    label: 'Urun Yonetimi',
    items: [
      { to: '/products', label: 'Urun Listesi', icon: Package, end: true },
      { to: '/products/new', label: 'Urun Ekle', icon: PackagePlus },
      { to: '/catalog/categories', label: 'Kategoriler', icon: Tags },
      { to: '/catalog/brands', label: 'Markalar', icon: ShieldCheck },
      { to: '/catalog/attributes', label: 'Nitelikler / Ozellikler', icon: ClipboardCheck },
      { to: '/products/category-mapping', label: 'Kategori Eslestirme', icon: Tags },
      { to: '/catalog/variants', label: 'Varyantlar', icon: ClipboardCheck },
      { to: '/catalog/tags', label: 'Etiketler', icon: Percent },
      { to: '/catalog/suppliers', label: 'Tedarikciler', icon: Building2 },
      { to: '/pricing/profit-rules', label: 'Fiyat Kurallari', icon: Calculator },
      { to: '/catalog/defaults', label: 'KDV / Birim / Desi', icon: Settings },
      { to: '/pricing/bulk-operations', label: 'Toplu Urun Islemleri', icon: Workflow },
      { to: '/products/import', label: 'Toplu Urun Yukleme', icon: UploadCloud },
      { to: '/products/publish-queue', label: 'Aktarim Listesi', icon: Send },
    ],
  },
  {
    label: 'Pazaryeri Yonetimi',
    items: [
      { to: '/marketplaces', label: 'Pazaryeri Hesaplari', icon: Link2, end: true },
      { to: '/marketplaces/onboarding', label: 'Kurulum Sihirbazi', icon: Rocket },
      { to: '/products/publish-queue', label: 'Urun Aktarim Listesi', icon: Send },
      { to: '/marketplaces/trendyol', label: 'Trendyol', icon: ShoppingBag },
      { to: '/marketplaces/hepsiburada', label: 'Hepsiburada', icon: ShoppingBag },
      { to: '/marketplaces/batch-results', label: 'Batch Sonuclari', icon: ClipboardList },
      { to: '/api-logs', label: 'Hata Merkezi', icon: AlertTriangle },
    ],
  },
  {
    label: 'Siparis Yonetimi',
    items: [
      { to: '/orders', label: 'Tum Siparisler', icon: ClipboardList, end: true },
      { to: '/orders/new', label: 'Yeni Siparisler', icon: ClipboardList },
      { to: '/orders/preparing', label: 'Hazirlanan Siparisler', icon: ClipboardList },
      { to: '/orders/ready-to-ship', label: 'Kargoya Hazir', icon: Truck },
      { to: '/orders/shipped', label: 'Kargodaki Siparisler', icon: Truck },
      { to: '/orders/cancel-returned', label: 'Iade/Iptal', icon: AlertTriangle },
    ],
  },
  {
    label: 'Operasyon',
    items: [
      { to: '/operations', label: 'Operasyon Merkezi', icon: Activity },
      { to: '/shipping', label: 'Kargo Yonetimi', icon: Truck },
      { to: '/payments', label: 'Odeme Yonetimi', icon: CreditCard },
      { to: '/accounting', label: 'Fatura/Cari', icon: Landmark },
    ],
  },
  {
    label: 'CMS',
    items: [
      { to: '/cms/pages', label: 'Sayfalar', icon: FileText },
      { to: '/cms/blog-posts', label: 'Blog', icon: FileText },
      { to: '/cms/blog-categories', label: 'Blog Kategorileri', icon: Tags },
      { to: '/cms/banners', label: 'Bannerlar', icon: FileImage },
      { to: '/cms/popups', label: 'Popup', icon: Megaphone },
      { to: '/cms/menus', label: 'Menu', icon: Menu },
      { to: '/cms/faqs', label: 'SSS', icon: HelpCircle },
      { to: '/cms/legal', label: 'Sozlesmeler / Cerez', icon: ReceiptText },
    ],
  },
  {
    label: 'Pazarlama',
    items: [
      { to: '/marketing/coupons', label: 'Kuponlar', icon: Percent },
      { to: '/marketing/coupons', label: 'Sepet Indirimleri', icon: Percent },
      { to: '/marketing/abandoned-carts', label: 'Terk Edilmis Sepet', icon: ShoppingBag },
      { to: '/marketing/email-templates', label: 'E-posta Sablonlari', icon: Mail },
      { to: '/marketing/sms-templates', label: 'SMS Sablonlari', icon: Smartphone },
      { to: '/marketing/whatsapp', label: 'WhatsApp Sablonlari', icon: MessageSquare },
      { to: '/marketing/feeds', label: 'Merchant / Meta Feed', icon: Megaphone },
      { to: '/marketing/pixels', label: 'Pixel Ayarlari', icon: FileCode2 },
    ],
  },
  {
    label: 'SEO',
    items: [
      { to: '/seo/settings', label: 'Meta Ayarlari', icon: SearchCheck },
      { to: '/seo/sitemap', label: 'Sitemap', icon: FileText },
      { to: '/seo/robots', label: 'Robots.txt', icon: FileCode2 },
      { to: '/seo/head-tags', label: 'Search Console / Head Kodlari', icon: ShieldCheck },
      { to: '/seo/languages', label: 'Coklu Dil', icon: Languages },
      { to: '/seo/locations', label: 'Lokasyonlar', icon: MapPinned },
      { to: '/seo/currencies', label: 'Doviz Ayarlari', icon: CircleDollarSign },
    ],
  },
  {
    label: 'B2B / Bayi',
    items: [
      { to: '/b2b/groups', label: 'Bayi Gruplari', icon: Building2 },
      { to: '/b2b/dealers', label: 'Bayi Firmalari', icon: Building2 },
      { to: '/b2b/prices', label: 'Ozel Fiyatlar', icon: CircleDollarSign },
      { to: '/b2b/transactions', label: 'Bakiye / Tahsilat', icon: Landmark },
      { to: '/b2b/dealers', label: 'Bayi XML Ayarlari', icon: UploadCloud },
    ],
  },
  {
    label: 'Fiyat Motoru',
    items: [
      { to: '/pricing/profit-rules', label: 'Kar Kurallari', icon: Calculator },
      { to: '/pricing/bulk-operations', label: 'Toplu Fiyat Operasyonlari', icon: Workflow },
      { to: '/pricing/profit-rules', label: 'Kategori Bazli Fiyatlama', icon: Tags },
      { to: '/pricing/bulk-operations', label: 'XML Bazli Fiyatlama', icon: UploadCloud },
      { to: '/pricing/calculator', label: 'Maliyet Dahil Hesaplama', icon: Calculator },
    ],
  },
  {
    label: 'Siparis Is Akisi',
    items: [
      { to: '/workflow/rules', label: 'Durum Gecis Kurallari', icon: Workflow },
      { to: '/workflow/rules', label: 'Kilitli Durumlar', icon: ShieldCheck },
      { to: '/workflow/notes', label: 'Siparis Notlari', icon: ClipboardList },
      { to: '/workflow/history', label: 'Operasyon Gecmisi', icon: FileText },
    ],
  },
  {
    label: 'Katalog Gelismis',
    items: [
      { to: '/catalog/relations', label: 'Urun Iliskileri', icon: Link2 },
      { to: '/catalog/custom-fields', label: 'Urun Ozel Alanlari', icon: ClipboardCheck },
      { to: '/catalog/barcodes', label: 'Toplu Barkod', icon: FileCode2 },
      { to: '/catalog/reviews', label: 'Urun Yorumlari', icon: MessageSquare },
    ],
  },
  {
    label: 'Genel',
    items: [
      { to: '/reports', label: 'Raporlar', icon: BarChart3 },
      { to: '/resources', label: 'Kaynaklar', icon: BookOpen },
      { to: '/settings', label: 'Ayarlar', icon: Settings },
    ],
  },
];

export const adminNavigationGroups = [
  {
    label: 'Balina Yonetimi',
    items: [
      { to: '/admin', label: 'Dashboard', icon: Gauge, end: true },
      { to: '/admin/companies', label: 'Musteri Firmalar', icon: Building2 },
      { to: '/admin/saas', label: 'Paketler Lisanslar', icon: Sparkles },
      { to: '/admin/saas', label: 'Abonelikler', icon: ClipboardCheck },
      { to: '/admin/payments', label: 'Odemeler Billing', icon: CircleDollarSign },
    ],
  },
  {
    label: 'Sistem Operasyonu',
    items: [
      { to: '/admin/reports', label: 'Sistem Sagligi', icon: BarChart3 },
      { to: '/admin/operations', label: 'Operasyon Merkezi', icon: Activity },
      { to: '/admin/queue', label: 'Queue Horizon', icon: Workflow },
      { to: '/admin/api-logs', label: 'API Loglari', icon: FileText },
      { to: '/admin/queue', label: 'Failed Jobs', icon: AlertTriangle },
      { to: '/admin/api-logs', label: 'Audit Log', icon: ShieldCheck },
      { to: '/admin/settings', label: 'Global Ayarlar', icon: Settings },
    ],
  },
];

export const navigationGroups = appNavigationGroups;
export const flatNavigation = navigationGroups.flatMap((group) => group.items);
